--1
SELECT E.*,UPPER(ENAME) AS UPPER_CASE FROM EMP1 E;

--2
SELECT E.*,LOWER(ENAME) AS LOWER_CASE FROM EMP1 E; 

--3
UPDATE ITEM SET ITEM_NAME = UPPER(ITEM_NAME);

--4
SELECT INITCAP('ab cd ef') from dual;

--5
SELECT * FROM EMP WHERE LENGTH(ENAME) = 4;

--6
SELECT ENAME,LENGTH(ENAME) FROM EMP;

--7
SELECT * FROM EMP WHERE LENGTH(ENAME) > 5;

--8
SELECT SUBSTR('ABCDEFGH',-5,1) FROM DUAL;
SELECT SUBSTR('GOWTHAM RAJ',-8) FROM DUAL;

--9
SELECT  SUBSTR(ENAME,1,2) || EMPNO || '@oracle.com' AS EMAIL FROM EMP1;
SELECT SUBSTR(ENAME,1,4) || SUBSTR(HIREDATE,-2) || '@tcs.com' AS EMAIL FROM EMP;

--10
SELECT * FROM EMP WHERE SUBSTR(ENAME,2,2) = 'LA';

--11
SELECT * FROM EMP WHERE SUBSTR(ENAME,1,1) = 'M';

--12
SELECT * FROM EMP WHERE SUBSTR(ENAME,1,1) IN('A','E','I','O','U');

--13
SELECT * FROM EMP WHERE SUBSTR(ENAME,1,1) = SUBSTR(ENAME,-1);

--14
SELECT * FROM EMP WHERE SUBSTR(ENAME,1,1) IN('A','E','I','O','U') AND SUBSTR(ENAME,-1) IN ('A','E','I','O','U') ;

--15
SELECT SUBSTR('AMEERPET HYDERABAD',1,8) FROM DUAL;  

--16
CREATE TABLE PERSON123(NAME VARCHAR(20), DOB DATE);


INSERT INTO PERSON123 VALUES('shreyas iyer','22-sep-94');

--17
ALTER TABLE PERSON123 ADD (PASSWORD VARCHAR2(20));

--18
UPDATE PERSON123 SET PASSWORD = SUBSTR(NAME,1,3) || SUBSTR(dob,-2,2);
SELECT * FROM PERSON123;


--19
SELECT LPAD('kiran',10,'#') FROM DUAL;
SELECT LPAD('gowtham',10,'$@') FROM DUAL;
SELECT LPAD('X',4,'X') FROM DUAL;
SELECT RPAD('ABCD',10,'#') FROM DUAL;
SELECT RPAD('KIRAN',10) || 'HELLO' FROM DUAL;
SELECT RPAD(ENAME,20) || SAL FROM EMP;

--2020.Generate the message if the account number is 1234567473 

--EXPECTED OUTPUT:
--Amount debited from XXXXXX7473
SELECT 'Amount debited from ' || LPAD(SUBSTR('1234567473',-4),10,'X') AS MESSAGE FROM DUAL;