--DML
--UPDATE TABLENAME SET COLUMNNAME = NEWVALUE WHERE COLUMNNAME = OLDVALUE

DROP TABLE EMP6;
CREATE TABLE EMP6(EMPNO NUMBER(4), ENAME VARCHAR2(10), SAL NUMBER, JOB VARCHAR(10), DEPARTMENT VARCHAR2(10));

INSERT INTO EMP6 VALUES (101, 'KIRAN', 6000, 'CLERK', 'RESEARCH');
INSERT INTO EMP6 VALUES (102, 'GOWTHAM', 10000, 'TEAM LEAD', 'IT');
INSERT INTO EMP6 VALUES (103, 'SATYA', 7000, 'CLERK', 'RESEARCH');
INSERT INTO EMP6 VALUES (104, 'KAVYA', 8000, 'ACCOUNTANT', 'FINANCE');
INSERT INTO EMP6 VALUES (105, 'PREETI', 12000, 'SALESMAN', 'SALES');
INSERT INTO EMP6 VALUES (106, 'SURYA', 20000, 'MANAGER', 'IT');
INSERT INTO EMP6 VALUES (107, 'ANUSHKA', 15000, 'DEVELOPER', 'IT');
INSERT INTO EMP6 VALUES (108, 'NITISH', 12000, 'SALESMAN', 'SALES');

commit;


UPDATE EMP6 SET SAL = 700 WHERE EMPNO = 103;

--2
UPDATE EMP6 SET JOB = 'MANAGER' ,SAL = (SAL + 3000) WHERE ENAME LIKE 'A%' AND ENAME LIKE '%A';


--3
UPDATE EMP6 SET SAL = SAL + 2000 WHERE DEPARTMENT = 'IT';

--4

UPDATE EMP6 SET SAL = SAL + 1000;

--5
UPDATE EMP6 SET SAL = 8500 WHERE ENAME = 'KAVYA';

--6
UPDATE EMP6 SET SAL = SAL + (SAL * 0.20) WHERE JOB = 'SALESMAN';

--7
UPDATE EMP6 SET SAL = SAL + (SAL * 0.10) WHERE SAL < 10000;

--8
ALTER TABLE EMP6 ADD ADDRESS VARCHAR2(10);

--9
UPDATE EMP6 SET ADDRESS = 'HYDERABAD' WHERE ENAME = 'KIRAN';

--10
UPDATE EMP6 SET ADDRESS = 'GUNTUR' WHERE DEPARTMENT = 'IT';

--11.Write a query to delete 104 employee salary
UPDATE EMP6 SET SAL = NULL WHERE EMPNO = 104;

--12
DELETE EMP6 WHERE ENAME = 'PREETI';

--13
DELETE EMP6 WHERE SAL < 9000;

--14
DELETE FROM EMP6;

--15
ROLLBACK;
SELECT * FROM USERS;

--16
INSERT INTO USERS VALUES (5 ,'THOMAS', 'thomas@gmail.com',1234567895);
SELECT * FROM USERS ORDER BY USER_ID ASC;

