--1
SELECT STATE,COUNT(*) FROM PERSON GROUP BY STATE; 

--2
SELECT STATE,GENDER,COUNT(*) AS NO_OF_EMPLOYES FROM PERSONS GROUP BY STATE,GENDER;

--3
SELECT * FROM EMP;
SELECT DEPTNO,COUNT(*) AS NO_OF_EMPLOYES FROM EMP GROUP BY DEPTNO;

--4
SELECT JOB,COUNT(*) AS NO_OF_EMPLOYES FROM EMP GROUP BY JOB;

--5
SELECT JOB,DEPTNO,COUNT(*) AS NO_OF_EMPLOYES  FROM EMP GROUP BY DEPTNO,JOB ORDER BY DEPTNO ASC;

--6
SELECT DEPTNO,AVG(SAL) FROM EMP GROUP BY DEPTNO;

--7
SELECT DEPTNO,MIN(SAL) AS MINIMUN_SAL,MAX(SAL) AS MAXIMUM_SAL FROM EMP GROUP BY DEPTNO;

--8
SELECT DEPTNO,COUNT(*) AS NO_OF_EMP , SUM(SAL) AS TOTAL_SAL, AVG(SAL) AS AVERAGE_SAL FROM EMP GROUP BY DEPTNO ;

--9
SELECT DEPTNO,COUNT(*) AS EMPS FROM EMP GROUP BY DEPTNO HAVING COUNT(*) > 3;

--10
SELECT STATE,COUNT(*) AS NO_OF_EMPLOYES FROM PERSON GROUP BY STATE HAVING COUNT(*) > 3;

--11
SELECT DEPTNO,SUM(SAL) AS TOTAL FROM EMP GROUP BY DEPTNO HAVING SUM(SAL) > 9000;

--12
SELECT EMPNO,ENAME FROM EMP111 WHERE ENAME IN(SELECT ENAME FROM EMP111 GROUP BY ENAME HAVING COUNT(*)> 1);

--13
SELECT TO_CHAR (HIREDATE, 'YYYY') AS YEAR, COUNT(*) AS NO_OF_EMPLOYES  FROM EMP GROUP BY TO_CHAR(HIREDATE ,'YYYY') HAVING COUNT (*) > 1;

--14
SELECT COUNT(*) AS NO_OF_EMPLOYES , TO_CHAR(HIREDATE, 'Q') AS QUATER FROM EMP GROUP BY TO_CHAR(HIREDATE,'Q') ORDER BY QUATER ;

--15
SELECT STATE,REGION,COUNT(*) AS NO_OF_EMPLOYES FROM EMP222 GROUP BY STATE,REGION; 

--16
SELECT DEPTNO,AVG(SAL) AS AVG_SAL FROM EMP GROUP BY DEPTNO HAVING AVG(SAL) > 2000;

--17
SELECT TO_CHAR(HIREDATE, 'MON') AS MONTH , COUNT(*) AS NO_OF_EMPLOYES FROM EMP WHERE TO_CHAR(HIREDATE,'MON') IN ('JAN','SEP') GROUP BY TO_CHAR(HIREDATE, 'MON');

--18
SELECT SUM(SAL),DEPTNO FROM EMP GROUP BY DEPTNO HAVING DEPTNO IN (10,30);

--19
