SELECT * FROM EMP;



--.Write a query to display the employees who are belongs to 20,30,50,70,90 departments from emp table by using in operator?  
SELECT * FROM EMP WHERE DEPTNO IN (10,20,30);


--2.Write a query to display whose employee names are SMITH,JONES,KING from emp table?
SELECT * FROM EMP WHERE ENAME IN ('SMITH','KING','JONES');

--3
SELECT * FROM EMP WHERE EMPNO IN(7902,7788,7900);

--4
SELECT * FROM EMP WHERE SAL IN (1250,3000,5000);

--5
SELECT * FROM EMP WHERE JOB NOT IN ('MANAGER','CLERK');

--6
SELECT * FROM EMP WHERE DEPTNO IN (10,20);

--Between and Operator

--1
SELECT * FROM EMP WHERE SAL BETWEEN 2000 AND 5000;

--2
SELECT * FROM EMP WHERE SAL NOT BETWEEN 2000 AND 5000;

--3
SELECT * FROM EMP WHERE HIREDATE BETWEEN '01-JAN-1981' AND '31-DEC-1981';

--4
SELECT * FROM EMP WHERE HIREDATE NOT BETWEEN '01-JAN-1981' AND '31-DEC-1981';

--5
SELECT * FROM EMP WHERE SAL BETWEEN 4000 AND 2000;

--3 IS NULL AND IS NOT NULL

--1
SELECT * FROM EMP WHERE COMM IS NULL;

--2
SELECT * FROM EMP WHERE COMM IS NOT NULL;

--3
SELECT * FROM EMP WHERE MGR IS NULL;

--15
SELECT * FROM EMP WHERE MGR IN (20,30);

--Arithmetic Operators

--1

SELECT ENAME,SAL,SAL*12 AS ANASAL FROM EMP;

--2
SELECT ENAME,HIREDATE,TRUNC((SYSDATE - HIREDATE)/365) AS EXPERIENCE FROM EMP;

--3
SELECT ENAME, 
        SAL,
    SAL * 0.10 AS TA,
    SAL * 0.20 AS HRA,
    SAL * 0.05 AS TAX,
    SAL + (SAL * 0.10) + (SAL * 0.20) - (SAL * 0.05) AS NETSAL FROM EMP;

--4
SELECT SAL, SAL + 1200 AS UPDATED_SALARY FROM EMP;