CREATE TABLE ITEM (
ITEM_NO NUMBER(5),
ITEM_NAME VARCHAR2(10),  
COLOR VARCHAR2(10),  
ITEM_SIZE  NUMBER(5),  
PRICE NUMBER(10),  
PUR_DATE  DATE        
);


INSERT INTO ITEM  VALUES (1, 'Shirt', 'Red', 40, 500,'02-JAN-2025');
INSERT INTO ITEM  VALUES (2, 'Pant', 'Blue', 42, 799,'10-NOV-2024');
INSERT INTO ITEM  VALUES (3, 'Saree', 'Pink', NULL, 1200,'19-MAR-2023');
INSERT INTO ITEM  VALUES (4, 'Chudidar', 'Green', 38, 899,'16-JAN-2025');
INSERT INTO ITEM  VALUES (5, 'Lehanga', 'Yellow', NULL, 1500,'24-AUG-2025');
INSERT INTO ITEM  VALUES (6, 'Shirt', 'Blue', 42, 550,'16-APR-2025');
INSERT INTO ITEM  VALUES (7, 'Pant', 'Black', 40, 750,'12-DEC-2024' );
INSERT INTO ITEM  VALUES (8, 'Saree', 'Black', NULL, 1300.00,'18-SEP-2024');

COMMIT;

--1
SELECT ITEM_NAME, COLOR, PRICE FROM ITEM WHERE PRICE > 800;

--2
SELECT * FROM ITEM 
WHERE COLOR NOT LIKE 'BLACK';

--3
SELECT * FROM ITEM
WHERE PUR_DATE > '01-FEB-2025';

--4
SELECT * FROM ITEM WHERE ITEM_NAME IN ('Shirt','Saree','Chudidar') ;

--5
SELECT * FROM ITEM WHERE ITEM_NAME = 'Shirt' AND ITEM_SIZE = 42;

--6
SELECT * FROM ITEM WHERE ITEM_NAME = 'Saree' AND COLOR = 'Pink';

--7
SELECT * FROM ITEM WHERE PUR_DATE >  '01-JAN-2024';

--8
SELECT * FROM ITEM WHERE PRICE BETWEEN 500 AND 1200;

--9
SELECT * FROM ITEM WHERE ITEM_SIZE IS NULL;

--10
SELECT * FROM ITEM WHERE ITEM_NAME LIKE 'S%';

--11
SELECT * FROM ITEM WHERE ITEM_NAME = 'Shirt' AND COLOR = 'Red' AND ITEM_SIZE = 40;

--12
SELECT * FROM ITEM 
WHERE ITEM_NAME IN ('Shirt','Pant')AND
PRICE BETWEEN 500 AND 800 
AND PUR_DATE LIKE '%25' AND
COLOR NOT IN ('Red','Black');
