--1.Write a query to display the employees whose ename start with S from emp table using like operator?

SELECT * FROM EMP WHERE ENAME LIKE 'S%' ;

--2
SELECT * FROM EMP WHERE ENAME LIKE '%S';

--3
SELECT * FROM EMP WHERE EMPNO LIKE '76%';

--4
SELECT * FROM EMP WHERE ENAME LIKE '%M%';

--5
SELECT * FROM EMP WHERE ENAME LIKE '__A%';

--6
SELECT * FROM EMP WHERE ENAME LIKE '__M%';

--7
SELECT * FROM EMP WHERE ENAME LIKE '____';

--8
SELECT * FROM EMP WHERE SAL LIKE '___';

--9
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE,'YY') LIKE '81';

--10
SELECT * FROM EMP WHERE EXTRACT (DAY FROM HIREDATE) = 29;

SELECT ENAME,
       EXTRACT(DAY FROM HIREDATE)   AS DAY,
       EXTRACT(MONTH FROM HIREDATE) AS MONTH,
       EXTRACT(YEAR FROM HIREDATE)  AS YEAR
FROM EMP;


--11
SELECT * FROM EMP WHERE ENAME LIKE '%AM%' OR ENAME LIKE '%AR%';

--12
SELECT * FROM EMP WHERE ENAME LIKE 'S%' OR ENAME LIKE '%S';

--13
SELECT * FROM EMP WHERE ENAME LIKE '%A' OR
                        ENAME LIKE '%E' OR
                        ENAME LIKE '%I' OR
                        ENAME LIKE '%O' OR
                        ENAME LIKE '%U';

SELECT *
FROM EMP
WHERE REGEXP_LIKE(ENAME, '[AEIOU]$');

--14
CREATE TABLE EMP555(ENAME VARCHAR2(20));

INSERT INTO EMP555 VALUES ('SIRISHA GAYATRI');
INSERT INTO EMP555 VALUES ('GAYATRI SIRISHA');
INSERT INTO EMP555 VALUES ('ANUSHKA SHETTY');
INSERT INTO EMP555 VALUES ('ANU SIRISHA RAI');
INSERT INTO EMP555 VALUES ('SURYA SURYA');

SELECT * FROM EMP555;
COMMIT;

SELECT * FROM EMP555 WHERE ENAME LIKE '%SIRISHA%';

--1
SELECT * FROM EMP WHERE JOB IN ('MANAGER','CLERK') AND SAL BETWEEN 1500 AND 3000 AND EXTRACT (YEAR FROM HIREDATE) = 1981 AND DEPTNO NOT IN(10,20);

--ALIAS NAME

SELECT ENAME AS EMP_NAME ,SAL,JOB FROM EMP WHERE SAL > 2000;

CREATE TABLE STAFF(STAFF_ID NUMBER(10), FIRST_NAME VARCHAR(20),LAST_NAME VARCHAR(20), POSITION VARCHAR(10), SALARY NUMBER);

INSERT INTO STAFF VALUES(1, 'ANUSHKA', 'SHETTY', 'MANAGER', 60000);
INSERT INTO STAFF VALUES(2, 'KIRAN', 'KUMAR', 'DEVELOPER', 48000);
INSERT INTO STAFF VALUES(3, 'GOWTHAM', 'RAJ', 'TEAM LEAD', 75000);
INSERT INTO STAFF VALUES(4, 'KAVYA', 'PAPA', 'HR', 51000);
INSERT INTO STAFF VALUES(5, 'PREETI', 'ZINTA', 'CLERK', 30000);
COMMIT;

SELECT * FROM STAFF;
--1
SELECT FIRST_NAME AS NAME , POSITION, SALARY FROM STAFF WHERE SALARY > 5000;



CREATE TABLE USERS (
    USER_ID NUMBER(10),
    NAME VARCHAR2(15),
    EMAIL VARCHAR2(20),
    PHONE_NUMBER VARCHAR2(15)
);

INSERT INTO USERS VALUES(1, 'ANUSHKA', 'anushka@gmail.com', '9876526229');         
INSERT INTO USERS VALUES(2, 'GOWTHAM', 'gowtham@gmail.com', '9912347810');
INSERT INTO USERS VALUES(3, 'SURYA',   'surya@gmail.com',   '9988776629'); 
INSERT INTO USERS VALUES(4, 'KAVYA PAPA','kavya@gmail.com', '9988776655');
COMMIT;

SELECT NAME AS USERNAME,EMAIL , PHONE_NUMBER FROM USERS WHERE PHONE_NUMBER LIKE '%29';

--Concatenation

SELECT EMPNO , ENAME ||' earns ' || SAL AS "EMPLOYEE DETAILS"
FROM EMP ;

SELECT ENAME || ' WORKS AS ' || JOB FROM EMP;

SELECT 'NARESH' || 'IT'AS RESULT FROM DUAL;

SELECT * FROM DUAL;