--1 1.Write a query to display total salary from emp table?
SELECT SUM(SAL) AS TOTAL_SALARY FROM EMP ;

--2.Write a query to display total salaries of all managers from emp table?
SELECT SUM(SAL) AS TOTAL_SALARY FROM EMP WHERE JOB = 'MANAGER';

--3
SELECT SUM(SAL) AS TOTAL_SALARY FROM EMP WHERE DEPTNO IN (10,30);

--4
SELECT AVG(SAL) AS AVG_SAL FROM EMP ;

--5
SELECT AVG(SAL) AS AVG_SAL FROM EMP WHERE JOB = 'CLERK';
SELECT * FROM EMP;

--6
SELECT MIN(SAL) FROM EMP ;

--7
SELECT MAX(SAL) FROM EMP;

--8
SELECT MAX(SAL),MIN(SAL) FROM EMP;

--9
SELECT COUNT(*) FROM EMP;

--10
SELECT COUNT(*) FROM EMP WHERE JOB = 'MANAGER';

--11
SELECT COUNT(*) FROM EMP WHERE DEPTNO IN (10,30);

--12
SELECT COUNT(*) FROM EMP WHERE TO_CHAR(HIREDATE, 'Q') = '4';

--13
SELECT COUNT(*) FROM EMP WHERE TO_CHAR(HIREDATE, 'YYYY') = '1981';

--14
SELECT COUNT(COMM) FROM EMP ;


CREATE TABLE FLIGHT 
(
FLIGHT_ID NUMBER(10),
DEPATURE_DATE DATE
);

INSERT INTO FLIGHT VALUES (101, '10-JAN-2023');
INSERT INTO FLIGHT VALUES (102, '25-JAN-2023');
INSERT INTO FLIGHT VALUES (103, '02-FEB-2023');
INSERT INTO FLIGHT VALUES (104, '10-JAN-2023');
INSERT INTO FLIGHT VALUES (105, '05-MAR-2023');

COMMIT;

--15
SELECT COUNT(*) AS NUMBER_OF_FLIGHTS
FROM FLIGHT
WHERE DEPATURE_DATE > TO_DATE('01-FEB-2023','DD-MON-YYYY');

--16
SELECT ENAME,SAL,COMM,SAL + NVL(COMM, 0) AS TOTAL_SALARY FROM EMP;

--17
SELECT ROUND(1.8) FROM DUAL;

--18 
SELECT ROUND(1.23456,3) FROM DUAL;

--19
Select round(1285.765,-1) from dual;

--1
SELECT ROUND(SAL,-3) FROM EMP;

Select SUBSTR('NARESH IT,HYDERABAD',1,9) from dual;

SELECT ROUND(45.953, -1), ROUND(45.936, 2) FROM dual;