CREATE TABLE STUDENTS (
    SID NUMBER,
    SNAME VARCHAR2(20),
    GENDER VARCHAR2(10),
    FEE NUMBER,
    DOB DATE
);
INSERT INTO STUDENTS VALUES (1,'SIVA','MALE',30000,DATE '2004-11-29');
INSERT INTO STUDENTS VALUES (2,'ARAVIND','MALE',30000,DATE '2003-1-1');
COMMIT;

SELECT * FROM STUDENTS;
SELECT table_name
FROM user_tables
WHERE table_name = 'STUDENT';

DROP TABLE STUDENT;
SELECT table_name FROM user_tables;



DELETE FROM STUDENTS WHERE SID = 2;
INSERT INTO STUDENTS VALUES (1,'SIVA','MALE',30000,DATE '2004-11-29');

INSERT INTO STUDENTS VALUES (2,'ARAVIND','MALE',30000,DATE '2003-1-1');
INSERT INTO STUDENTS VALUES('','SURYA','',30000,'');
SELECT * FROM STUDENTS;

CREATE TABLE PRODUCT(PID NUMBER, PNAME VARCHAR(20), CATEGORY VARCHAR(20), PRICE NUMBER);
INSERT INTO PRODUCT VALUES(1, 'LED TV', 'ELECTRONICS',25000);
INSERT INTO PRODUCT VALUES(2, 'MOBILE', 'ELECTRONICS', 27000);
INSERT INTO PRODUCT VALUES(3, 'FRIDGE', 'ELECTRONICS', 30000);
INSERT INTO PRODUCT VALUES(4, 'WASHING MACHINE', 'ELECTRONICS', 35000);
SELECT * FROM PRODUCT;
SELECT PNAME FROM PRODUCT;
SELECT PNAME , CATEGORY FROM PRODUCT;
SELECT PNAME, CATEGORY , PRICE FROM PRODUCT;
COMMIT;

INSERT ALL
INTO PRODUCT VALUES(5, 'FAN', 'ELECTRONICS',4500)
INTO PRODUCT VALUES(6, 'LIGHT','ELCTRONICS',150)
INTO PRODUCT VALUES(7, 'PROJECTOR', 'ELECTRONICS', 10000)
SELECT * FROM DUAL;
SELECT * FROM PRODUCT;

SELECT * FROM PRODUCT;

SELECT * FROM PRODUCT WHERE PRICE > 20000;
SELECT * FROM PRODUCT WHERE CATEGORY = 'ELECTRONICS';
SELECT * FROM PRODUCT WHERE PRICE > 1000 OR PRICE <500;
SELECT * FROM PRODUCT WHERE PID = 1 AND PID = 1;
